<?php

namespace App\Repositories;

use App\Models\SendMail;
use JasonGuru\LaravelMakeRepository\Repository\BaseRepository;
//use Your Model

/**
 * Class MailsRepository.
 */
class MailsRepository extends BaseRepository
{
    /**
     * @return string
     *  Return the model
     */
    public function model()
    {
        return SendMail::class;
    }

    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
