<?php

namespace App\Repositories;

use App\Models\Register;
use JasonGuru\LaravelMakeRepository\Repository\BaseRepository;

//use Your Model

/**
 * Class RegisterRepository.
 */
class RegisterRepository extends BaseRepository
{
    /**
     * @return string
     *  Return the model
     */
    public function model()
    {
        return Register::class;
    }

    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
