<?php

namespace App\Repositories;

use App\Models\SiteConfig;
use JasonGuru\LaravelMakeRepository\Repository\BaseRepository;

//use Your Model

/**
 * Class SiteConfigRepository.
 */
class SiteConfigRepository extends BaseRepository
{
    /**
     * @return string
     *  Return the model
     */
    public function model()
    {
        return SiteConfig::class;
    }

    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
